### ISSUE TITLE
HC1 - Trellis - Judge.me

### ISSUE THREAD

**Issue by AzizTlx** [trellixio/trybeans-mintlify#1]
The new Beans and Judge.me integration has plenty of feature that allows merchants to get the most of their loyalty program. Yet so few merchants understand how it works.
Write a help center article that explains to merchants how to integration Beans with Judge.me and how to best leverage the functionalities of the integration.

- The article should cover all the functionalities of the Product Requirement Document: https://trybeans.notion.site/Judge-me-5a09dfe2648142719c06f3ee1215b9b7?pvs=4

- The article should follow the guideline on how to write a help center article: https://trybeans.slite.page/p/GVB3j5CToj43kV/Help-Center

- Special attention should be given to screenshot and screencast.

- Make sure to study the official help center to get a good understanding of expectation: https://help.trybeans.com/
- The article should be on Google Doc with the link shared with your manager

**Comment by AzizTlx** [comment]
link to onaivi work on judge me : https://docs.google.com/document/d/1Yt4VLXGm7g8oYohe-mA3pMvRkRAot7mGt0fWEDsbt20/edit?usp=sharing

**Comment by dlionel** [comment]
@Onaivio Structure your document into these steps:

### Setup
Explain how to set up Judge.me and Beans Integration. Use a screencast. 
- 1 screenscast on how to set up

### Rules 
For each rule, briefly explain its use and add a screencast of how it works. 
-  1 screencast on the storefront for each rule: How customers leave review and earn points  

### Logs 
Explain the logs functionality and add a screenshot
- 1 screenshot of the log page

### Status 
Explain each functionality of the status page. 
- 1 screenshot of the status page

All screencast should be less than 30 seconds. 

- Always follow the official guideline for the screenshots and screencasts
- Always use the official demo store when taking screenshots

**Comment by Onaivio** [comment]
The link to the update on the judge.me documentation - [https://docs.google.com/document/d/1Yt4VLXGm7g8oYohe-mA3pMvRkRAot7mGt0fWEDsbt20/edit?usp=sharing](https://docs.google.com/document/d/1Yt4VLXGm7g8oYohe-mA3pMvRkRAot7mGt0fWEDsbt20/edit?usp=sharing)

**Comment by AzizTlx** [comment]
Hi Onaivi , when doing a screencast , please make sure we don't see your other tabs , also try to take more accurate screencasts.

**Comment by Onaivio** [comment]
Noted sir, let me redo it

**Comment by dlionel** [comment]
When recording video make sure to use the trim functionnality in order to trim unrelevant parts such as slow loading pages: https://learn.screencastify.com/hc/en-us/articles/360049153274-How-can-I-cut-and-or-rearrange-my-video-clips-in-the-Editor-

**Comment by dlionel** [comment]
@Onaivio  I have reviewed your submission.

1. Fix the comments in the google doc.
2. Once the comments are fixed update the screenshots with the new guideline
3. Once you are done checkout the github repo: https://github.com/trellixio/trybeans-mintlify
4. Create a new branch integrations/judgeme
5. Follow the steps in the readme.md to install the project and run it on your local machine
6. Add the content to integrations/judgeme.mdx 
7. Commit your work and create a pull request to the main branch. 
8. Attach your PR to this issue.

**Comment by Onaivio** [comment]
[Merge pull request](https://github.com/trellixio/trybeans-mintlify/commit/fa7b12f82bc280e944d3504f2d9370dc526fba74) https://github.com/trellixio/trybeans-mintlify/pull/4 [from trellixio/feature/integrations/judgeme](https://github.com/trellixio/trybeans-mintlify/commit/fa7b12f82bc280e944d3504f2d9370dc526fba74)

**Comment by dlionel** [comment]
Done the Judge documentation has been added #26
