### ISSUE TITLE
HC2 - Trellis - klaviyo

### ISSUE THREAD

**Issue by AzizTlx** [trellixio/trybeans-mintlify#2]
The new Beans and klaviyo integration has plenty of feature that allows merchants to get the most of their loyalty program. Yet so few merchants understand how it works.
Write a help center article that explains to merchants how to integration Beans with klaviyo and how to best leverage the functionalities of the integration.

- The article should cover all the functionalities of the Product Requirement Document: https://trybeans.notion.site/Klaviyo-a08b898f354c414cb8e4a51d4e840f2f?pvs=4

- The article should follow the guideline on how to write a help center article: https://trybeans.slite.page/p/GVB3j5CToj43kV/Help-Center

- Special attention should be given to screenshot and screencast.

- Make sure to study the official help center to get a good understanding of expectation: https://help.trybeans.com/
- The article should be on Google Doc with the link shared with your manager

**Comment by AzizTlx** [comment]
isaac's work : https://docs.google.com/document/d/1hBrQM5_ZahsRkS7t6BwNkaktWnaQ2XZF9ogTEg4H2aI/edit?usp=sharing

**Comment by dlionel** [comment]
@Aduralere54256703  Structure your document into these steps:

### Setup
Explain how to set up Klaviyo and Beans Integration. Use a screencast. 
- 1 screenscast on how to set up

### Metrics
For each rule, briefly explain its use case and add the list of property for that metric. 
- 1 screenshot of a metric event in the Klaviyo interface
![image](https://github.com/trellixio/trybeans-mintlify/assets/7291417/5ddf31ca-b40e-4165-ab28-97d753644091)

### Events Logs 
Explain the logs functionality and add a screenshot
- 1 screenshot of the log page

### Preferences 
Explain each functionality of the status page. 
- 1 screenshot of the status page

### Status 
Explain each functionality of the status page. 
- 1 screenshot of the status page

All screencast should be less than 30 seconds. 

- Always follow the official guideline for the screenshots and screencasts
- Always use the official demo store when taking screenshots

**Comment by dlionel** [comment]
@Aduralere54256703  I have reviewed your submission.

- Fix the comments in the google doc.
- Once the comments are fixed update the screenshots with the new guideline
- Once you are done checkout the github repo: https://github.com/trellixio/trybeans-mintlify
- Create a new branch `integrations/klaviyo`
- Follow the steps in the readme.md to install the project and run it on your local machine
- Add the content to `integrations/klaviyo.mdx`
- Commit your work and create a pull request to the main branch.
- Attach your PR to this issue.
