### ISSUE TITLE
HC6 - Boiler - Members management 

### ISSUE THREAD

**Issue by AzizTlx** [trellixio/trybeans-mintlify#8]
### Members management

Write an article about how merchant manage members in their rewards program. 

The article should contains the following section:
- Add a member
- Update profile
- Update email addresses
- Deactivate a member 
  - in this section, also explain in which case an account can be automatically deactivated, for example when there is a spam report.
- Activate a member
- Delete a member
- List, filter, and search members
- Perform bulk actions

This article is a bit long so special attention needs to be taken to formatting and structuring.

- Use Shopify document as inspiration : https://help.shopify.com/en/manual/customers/manage-customers
- The article should follow the guideline on how to write a help center article: https://trybeans.slite.page/p/GVB3j5CToj43kV/Help-Center
- Special attention should be given to screenshot and screencast.
- Make sure to study the official help center to get a good understanding of expectation: https://help.trybeans.com/

### Deliverable 
Your work has to be delivered on a google doc, if you are not able to create one ask your manager to help you.

### Deadline
You have 6 hours to deliver this task

**Comment by Aduralere54256703** [comment]
Google document link: https://docs.google.com/document/d/1l8qm5HJC2-JZ7b6eW9Vmopf9SqKrmeCsnzzqYMK2v7s/edit?usp=sharing
